# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: HigherLevel.dev
email: adam@higherleveldev.com
description: >- # this means to ignore newlines until "baseurl:"
  The Higher Level Dev Guide documents how to direct AI software engineering
  agents to build software much more rapidly. Learn how to leverage AI for
  efficient and advanced software development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://higherlevel.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: higherleveldev
github_username:  higherleveldev

# Build settings
theme: jekyll-theme-prologue
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-timeago

# GitHub Pages settings
remote_theme: chrisbobbe/jekyll-theme-prologue

# Prologue theme settings
collections: [sections]

# Jekyll-timeago settings
jekyll_timeago:
  depth: 2
  today: 'today'
  yesterday: 'yesterday'
  tomorrow: 'tomorrow'
  and: 'and'
  suffix: 'ago'
  prefix: ''
  suffix_future: ''
  prefix_future: 'in'
  years: 'years'
  year: 'year'
  months: 'months'
  month: 'month'
  weeks: 'weeks'
  week: 'week'
  days: 'days'
  day: 'day'

# The following settings are NECESSARY for the Prologue theme to function properly.
# Please add this part to your _config.yml file.
avatar: assets/images/avatar.jpg
# You'll want to customize url and baseurl for your own site:
# url is the full website URL
# baseurl is the website's URL without the hostname
# If you're hosting on GitHub Pages, baseurl should be set to "/" or "" (empty string)

# Optional settings
# You can use this to add a subtitle to your site
# subtitle: "A responsive Jekyll theme"
# You can use this to make a list of links in the nav bar
nav:
  - {title: "Home", url: "/"}
  - {title: "About", url: "/about/"}

# You might want to keep some of the defaults below:
# author is used in a few places, especially for the author meta tag
author: Your Name
# add your Google Analytics ID here if you have one and want to use it
google_analytics:
# Used by jekyll-seo-tag
social:
  name: Your Name
  links:
    - https://github.com/higherleveldev

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
